version: "3"
services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
